services:
  - type: web
    name: urara-admin
    env: node
    plan: free
    buildCommand: npm install && npm run build --workspace=apps/admin
    startCommand: npm run start --workspace=apps/admin
    envVars:
      - key: NODE_VERSION
        value: 20.18.0

  - type: web
    name: urara-app
    runtime: static
    buildCommand: npm install && npm run build:web --workspace=apps/mobile
    staticPublishPath: apps/mobile/dist
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
