import type { Companion, Customer, Reservation, Venue } from "./types";

export const MOCK_VENUES: Venue[] = [
  {
    id: "v1",
    name: "甲府 個室居酒屋 花月",
    address: "山梨県甲府市丸の内1-2-3",
    prefecture: "山梨県",
    city: "甲府市",
    venueType: "restaurant",
    isActive: true,
  },
  {
    id: "v2",
    name: "昭和町 宴会場 かがやき",
    address: "山梨県中巨摩郡昭和町清水新居1-1",
    prefecture: "山梨県",
    city: "昭和町",
    venueType: "banquet_hall",
    isActive: true,
  },
  {
    id: "v3",
    name: "石和温泉 大広間 雅",
    address: "山梨県笛吹市石和町市部2-4-1",
    prefecture: "山梨県",
    city: "笛吹市石和町",
    venueType: "banquet_hall",
    isActive: true,
  },
  {
    id: "v4",
    name: "甲府 イベントホール SORA",
    address: "山梨県甲府市国母5-6-7",
    prefecture: "山梨県",
    city: "甲府市",
    venueType: "event_venue",
    isActive: true,
  },
];

export const MOCK_COMPANIONS: Companion[] = [
  { id: "c1", fullName: "佐藤 A子", phoneNumber: "090-1111-2222", lineId: "sato_a", status: "active" },
  { id: "c2", fullName: "鈴木 B美", phoneNumber: "090-2222-3333", lineId: "suzuki_b", status: "active" },
  { id: "c3", fullName: "高橋 C香", phoneNumber: "090-3333-4444", lineId: "takahashi_c", status: "active" },
  { id: "c4", fullName: "田中 D奈", phoneNumber: "090-4444-5555", lineId: "tanaka_d", status: "active" },
  { id: "c5", fullName: "伊藤 E菜", phoneNumber: "090-5555-6666", lineId: "ito_e", status: "inactive" },
];

export const MOCK_CUSTOMERS: Customer[] = [
  { id: "u1", fullName: "山本 太郎", phoneNumber: "080-1234-5678", identityVerificationStatus: "verified" },
  { id: "u2", fullName: "小林 次郎", phoneNumber: "080-2345-6789", identityVerificationStatus: "unverified" },
  { id: "u3", fullName: "中村 三郎", phoneNumber: "080-3456-7890", identityVerificationStatus: "pending_review" },
];

const now = new Date();
function hoursFromNow(h: number) {
  return new Date(now.getTime() + h * 60 * 60 * 1000).toISOString();
}

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: "r1",
    customerId: "u1",
    contactName: "山本 太郎",
    contactPhone: "080-1234-5678",
    venueId: "v1",
    bookingType: "now",
    requestedDatetime: now.toISOString(),
    guestCount: 6,
    companionCount: 2,
    durationHours: 2,
    travelFee: 0,
    paymentMethod: "card",
    notes: "20時までに来てほしいです。",
    status: "received",
    confirmedAt: null,
    assignedCompanionIds: [],
    statusHistory: [
      { fromStatus: null, toStatus: "received", changedBy: "system", changedAt: now.toISOString() },
    ],
    createdByAdmin: false,
  },
  {
    id: "r2",
    customerId: "u2",
    contactName: "小林 次郎",
    contactPhone: "080-2345-6789",
    venueId: "v2",
    bookingType: "scheduled",
    requestedDatetime: hoursFromNow(30),
    guestCount: 10,
    companionCount: 3,
    durationHours: 2,
    travelFee: 3000,
    paymentMethod: "cash",
    notes: "接待利用。落ち着いた雰囲気希望。",
    status: "arranging",
    confirmedAt: null,
    assignedCompanionIds: ["c1"],
    statusHistory: [
      { fromStatus: null, toStatus: "received", changedBy: "system", changedAt: hoursFromNow(-2) },
      { fromStatus: "received", toStatus: "arranging", changedBy: "admin", changedAt: hoursFromNow(-1) },
    ],
    createdByAdmin: false,
  },
  {
    id: "r3",
    customerId: "u1",
    contactName: "山本 太郎",
    contactPhone: "080-1234-5678",
    venueId: "v3",
    bookingType: "scheduled",
    requestedDatetime: hoursFromNow(50),
    guestCount: 8,
    companionCount: 2,
    durationHours: 3,
    travelFee: 5000,
    paymentMethod: "card",
    notes: "",
    status: "confirmed",
    confirmedAt: hoursFromNow(-3),
    assignedCompanionIds: ["c2", "c3"],
    statusHistory: [
      { fromStatus: null, toStatus: "received", changedBy: "system", changedAt: hoursFromNow(-10) },
      { fromStatus: "received", toStatus: "arranging", changedBy: "admin", changedAt: hoursFromNow(-6) },
      { fromStatus: "arranging", toStatus: "confirmed", changedBy: "admin", changedAt: hoursFromNow(-3) },
    ],
    createdByAdmin: false,
  },
  {
    id: "r4",
    customerId: null,
    contactName: "電話予約: 渡辺様",
    contactPhone: "090-9999-8888",
    venueId: "v4",
    bookingType: "scheduled",
    requestedDatetime: hoursFromNow(-20),
    guestCount: 12,
    companionCount: 4,
    durationHours: 2,
    travelFee: 4000,
    paymentMethod: "cash",
    notes: "電話にて受付。",
    status: "completed",
    confirmedAt: hoursFromNow(-30),
    assignedCompanionIds: ["c1", "c2", "c3", "c4"],
    statusHistory: [
      { fromStatus: null, toStatus: "received", changedBy: "admin(電話登録)", changedAt: hoursFromNow(-40) },
      { fromStatus: "received", toStatus: "arranging", changedBy: "admin", changedAt: hoursFromNow(-35) },
      { fromStatus: "arranging", toStatus: "confirmed", changedBy: "admin", changedAt: hoursFromNow(-30) },
      { fromStatus: "confirmed", toStatus: "completed", changedBy: "admin", changedAt: hoursFromNow(-18) },
    ],
    createdByAdmin: true,
  },
  {
    id: "r5",
    customerId: "u3",
    contactName: "中村 三郎",
    contactPhone: "080-3456-7890",
    venueId: "v1",
    bookingType: "scheduled",
    requestedDatetime: hoursFromNow(5),
    guestCount: 4,
    companionCount: 1,
    durationHours: 2,
    travelFee: 0,
    paymentMethod: "card",
    notes: "当日体調不良のためキャンセル希望。",
    status: "cancelled",
    confirmedAt: null,
    assignedCompanionIds: [],
    statusHistory: [
      { fromStatus: null, toStatus: "received", changedBy: "system", changedAt: hoursFromNow(-8) },
      { fromStatus: "received", toStatus: "cancelled", changedBy: "customer", changedAt: hoursFromNow(-1), note: "当日キャンセル（ペナルティ¥13,200）" },
    ],
    createdByAdmin: false,
  },
];
